### ISSUE TITLE
P404

### ISSUE THREAD

**Issue by ybotmallah** [peterkvt80/Muttlee#1]
When following the instructions I put my own pages In the teletext folder that I created correctly assigning the page numbers In wxTed, I then run OnAir.sh it correctly imports to the private folder then when accessing the ip it shows p404 Ceefax. Can anyone help me out?

Kind regards,
Toby Hallam

**Comment by peterkvt80** [comment]
The ip version does not update automatically. Your page isn't live. It
updates every few days when I get around to it.

**Comment by ybotmallah** [comment]
So the install on my install of debian only updates when you tell it to?

**Comment by peterkvt80** [comment]
Sorry, I thought you were using my server on which I don't run onair.sh
everyday. I find I need to do
sudo ./onair.sh
because of the way permissions are set,.
Peter

**Comment by ybotmallah** [comment]
That sorted my problem! Thanks for the help, Muttlee will be so good when its finished.
