### ISSUE TITLE
Page renaming

### ISSUE THREAD

**Issue by peterkvt80** [peterkvt80/Muttlee#15]
When a teletext service is used from a repo, the filenames need to be changed to p100.tti etc. This means that the files need to be processed by a bash script each time that the repository changes. The problem is that the services are only updated twice daily. I don't run the processing often as it would increase the wear out the SD card.

One solution would be for the server to map each page number to a file. When the client requests page 475 then a function would scan all the .tti files for "PN,475" and when it finds it, returns p475-digitiserTips.tti. Maybe generate a lookup table so you'd only need to scan when the repo changes.

Another solution that is much simpler but uses more memory is to run the script that renames the files but to put the pages into /tmp/muttleeservice/[name of service]. Then the bash script can be run whenever a repo is updated.

**Comment by dannya** [comment]
I feel like I've implemented a good solution in the above pull request.
